In [ ]:
import numpy as np
print(np.__version__)

1.26.4


In [ ]:
import numpy as np
x = np.array([1,0,0,0])
print("original array")
print(x)
print(np.array(x))
x = (np.array(x))
x = np.array([0,0,0,0])
print(np.array(x))

original array
[1 0 0 0]
[1 0 0 0]
[0 0 0 0]


In [ ]:
import numpy as np
array = np.array([1,-2,np.inf, -np.inf,0,3.5])
result_pos_inf = np.isposinf(array)
result_neg_inf = np.isneginf(array)
print("result_pos_inf is",result_pos_inf)
print("result_neg_inf is",result_neg_inf)

result_pos_inf is [False False  True False False False]
result_neg_inf is [False False False  True False False]


In [ ]:
import numpy as np
a = np.array([1,0,np.nan, np.inf])
print(a)
print("Test element wise for nan ")
print(np.isnan(array))

[ 1.  0. nan inf]
Test element wise for nan 
[False False False False False False]


In [ ]:
import numpy as np
array = np.arange(30,70)
print(array)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]


In [ ]:
#print only even
import numpy as np
array = np.arange(30,70,2)
print(array)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68]


In [ ]:
#to create 3x3 identity matrix
import numpy as np
array = np.identity(3)

print(array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#perform add , sub, multiply of two matrix
import numpy as np
a= np.array([[1,2],[3,4],])
b= np.array([[7,8],[3,3],])
addition = a+b
subtraction = a-b
multiplication = np.dot(a,b)
print("matrix a:")
print(a)
print("\nmatrix b:")
print(b)
print("addition of a and b : ")
print(addition)
print("subtraction of a and b : ")
print(subtraction)
print("multiplication of a and b : ")
print(multiplication)



matrix a:
[[1 2]
 [3 4]]

matrix b:
[[7 8]
 [3 3]]
addition of a and b : 
[[ 8 10]
 [ 6  7]]
subtraction of a and b : 
[[-6 -6]
 [ 0  1]]
multiplication of a and b : 
[[13 14]
 [33 36]]


In [ ]:
#to reverse 4x4 array
import numpy as np
a= np.array([[1,2,5,6],[3,4,7,8],[1,2,3,4],[5,6,7,8]])
print(a)
print(a[: : -1])


[[1 2 5 6]
 [3 4 7 8]
 [1 2 3 4]
 [5 6 7 8]]
[[5 6 7 8]
 [1 2 3 4]
 [3 4 7 8]
 [1 2 5 6]]


In [ ]:
#to transpose given 4x4 matrix
import numpy as np
a= np.array([[1,2,5,6],[3,4,7,8],[1,2,3,4],[5,6,7,8]])
print(a)
print(np.transpose(a))

[[1 2 5 6]
 [3 4 7 8]
 [1 2 3 4]
 [5 6 7 8]]
[[1 3 1 5]
 [2 4 2 6]
 [5 7 3 7]
 [6 8 4 8]]


In [ ]:
#create new array from given array from swapping first and last,second and third  column
import numpy as np
a= np.array([[1,2,5,6],[3,4,7,8],[1,2,3,4],[5,6,7,8]])
print(a)

